#服务端口
server:
  port: 8002
  #服务名
spring:
  application:
    name: service-oss
  
  #环境设置：dev、test、prod
  profiles:
    active: dev

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  
#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tMtg1yCgnXgRWCP6CUd
      keysecret: Sv6JBOZXZtUH0lnuHlp7mCqo7dsAkN
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: ty-eduservice
#      keyid: LTAI4FvvVEWiTJ3GNJJqJnk7
#      keysecret: 9st82dv7EvFk9mTjYO1XXbM632fRbG
#      #bucket可以在控制台创建，也可以使用java代码创建
#      bucketname: edu-guli-1010