# 服务端口
server:
  port: 8003
  # 服务名
spring:
  application:
    name: ty-service-vod
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # 最大上传单个文件大小：默认1M
  servlet:
    multipart:
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB

  #阿里云 vod
  #不同的服务器，地址不同
aliyun:
  vod:
    file:
#      keyid: LTAI4FvvVEWiTJ3GNJJqJnk7
#      keysecret: 9st82dv7EvFk9mTjYO1XXbM632fRbG
      keyid: LTAI5tMtg1yCgnXgRWCP6CUd
      keysecret: Sv6JBOZXZtUH0lnuHlp7mCqo7dsAkN
  
