# 服务端口
server:
  port: 8006
  # 服务名
spring:
  application:
    name: ty-service-ucenter

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ty_edu?serverTimezone=GMT%2B8
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        #最小空闲
        min-idle: 0


  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 微信开放平台 appid
wx:
  open:
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url
    redirect_url: http://guli.shop/api/ucenter/wx/callback


#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/ty/educenter/mapper/xml/*.xml

  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl